-- ============================================================
-- FantAmici · schema database (Supabase / PostgreSQL)
-- Copia tutto questo testo, vai su Supabase > SQL Editor > New query,
-- incolla ed esegui (RUN). Crea le 3 tabelle e i permessi necessari.
-- ============================================================

-- 1) LEGHE (ogni lega è salvata come un singolo oggetto JSON)
create table if not exists public.leagues (
  code        text primary key,
  data        jsonb not null,
  updated_at  timestamptz not null default now()
);

-- 2) RECENSIONI (mostrate in fondo alla home, pubbliche)
create table if not exists public.reviews (
  id          bigint generated by default as identity primary key,
  name        text not null,
  rating      int  not null check (rating between 1 and 5),
  text        text not null,
  created_at  timestamptz not null default now()
);

-- 3) FEEDBACK / SEGNALAZIONI BUG (privati: li leggi tu da Supabase)
create table if not exists public.feedback (
  id          bigint generated by default as identity primary key,
  kind        text not null,        -- 'bug' oppure 'idea'
  email       text,
  text        text not null,
  created_at  timestamptz not null default now()
);

-- ============================================================
-- PERMESSI (Row Level Security)
-- NB: per un gioco tra amici teniamo le cose semplici. La "sicurezza"
-- delle leghe sta nel codice segreto a 6 caratteri. Le recensioni sono
-- pubbliche; i feedback si possono inserire ma NON leggere dal sito.
-- ============================================================

alter table public.leagues  enable row level security;
alter table public.reviews  enable row level security;
alter table public.feedback enable row level security;

-- LEGHE: chiunque (con il codice) può leggere, creare e aggiornare.
drop policy if exists "leagues_read"   on public.leagues;
drop policy if exists "leagues_write"  on public.leagues;
drop policy if exists "leagues_update" on public.leagues;
create policy "leagues_read"   on public.leagues for select using (true);
create policy "leagues_write"  on public.leagues for insert with check (true);
create policy "leagues_update" on public.leagues for update using (true) with check (true);

-- RECENSIONI: lettura pubblica, inserimento libero (niente cancellazione dal sito).
drop policy if exists "reviews_read"  on public.reviews;
drop policy if exists "reviews_write" on public.reviews;
create policy "reviews_read"  on public.reviews for select using (true);
create policy "reviews_write" on public.reviews for insert with check (true);

-- FEEDBACK: solo inserimento (nessuna lettura pubblica → li vedi tu nel pannello Supabase).
drop policy if exists "feedback_write" on public.feedback;
create policy "feedback_write" on public.feedback for insert with check (true);

-- ============================================================
-- REALTIME · abilita gli aggiornamenti in tempo reale
-- (le classifiche si aggiornano da sole quando l'host assegna punti).
-- Se la tabella è già nella publication, l'errore si può ignorare.
-- ============================================================
alter publication supabase_realtime add table public.leagues;
alter publication supabase_realtime add table public.reviews;

-- Fine. Ora copia URL e "anon public key" del progetto dentro index.html.
